-- MySQL Script generated by MySQL Workbench
-- alx 25 mar 2021 22:16:06 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema c19pm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c19pm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c19pm` DEFAULT CHARACTER SET utf8 ;
USE `c19pm` ;

-- -----------------------------------------------------
-- Table `c19pm`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c19pm`.`t_user` ;

CREATE TABLE IF NOT EXISTS `c19pm`.`t_user` (
  `idUser` INT(11) NOT NULL,
  `username` VARCHAR(45) NULL,
  `login` VARCHAR(25) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c19pm`.`dayStat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c19pm`.`dayStat` ;

CREATE TABLE IF NOT EXISTS `c19pm`.`dayStat` (
  `idday` INT(11) NOT NULL,
  `date` DATE NULL,
  `numberOfTests` INT(11) NULL,
  `numberOfNewCases` INT(11) NULL,
  `numberOfImportedCases` INT(11) NULL,
  `numberOfCommunityCases` INT(11) NULL,
  `numberOfContactCases` INT(11) NULL,
  `numberOfHealed` INT(11) NULL,
  `numberOfDeath` INT(11) NULL,
  `TotalCases` INT(11) NULL,
  `TotalHealed` INT(11) NULL,
  `nbreDecesTotal` INT(11) NULL,
  `extratedDate` DATE NULL,
  `filename` VARCHAR(45) NULL,
  `t_user_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idday`),
  INDEX `fk_dayStat_t_user1_idx` (`t_user_idUser` ASC),
  CONSTRAINT `fk_dayStat_t_user1`
    FOREIGN KEY (`t_user_idUser`)
    REFERENCES `c19pm`.`t_user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c19pm`.`location` ;

CREATE TABLE IF NOT EXISTS `c19pm`.`location` (
  `locationName` VARCHAR(45) NULL,
  `locNumberofNewCases` INT(11) NULL,
  `locTotalCases` INT(11) NULL,
  `administrativeLevel` ENUM('city', 'district', 'department') NULL,
  `dayStat_idday` INT(11) NOT NULL,
  INDEX `fk_location_dayStat1_idx` (`dayStat_idday` ASC),
  CONSTRAINT `fk_location_dayStat1`
    FOREIGN KEY (`dayStat_idday`)
    REFERENCES `c19pm`.`dayStat` (`idday`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
